# Generated by Django 5.2 on 2025-04-26 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="文件ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="图片标题")),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="文件名称"),
                ),
                (
                    "object_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="对象存储名称"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="", max_length=100, verbose_name="内容类型"
                    ),
                ),
                ("size", models.IntegerField(default=0, verbose_name="文件大小(字节)")),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="访问URL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "图片",
                "verbose_name_plural": "图片",
                "db_table": "base_image",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="用户ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                (
                    "email",
                    models.EmailField(max_length=255, unique=True, verbose_name="邮箱"),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="昵称"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "未激活"),
                            ("blocked", "已封禁"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "base_user",
                "ordering": ["-created_at"],
            },
        ),
    ]
