# Generated by Django 5.2 on 2025-04-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="file_ext",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="文件扩展名"
            ),
        ),
    ]
