# Generated by Django 5.2 on 2025-05-05 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_image_file_ext"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                (
                    "config_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="配置ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, verbose_name="配置键")),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="配置值"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="配置描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="base.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户配置",
                "verbose_name_plural": "用户配置",
                "db_table": "base_user_config",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "key")},
            },
        ),
    ]
