# Generated by Django 5.2 on 2025-08-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_userconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_subscription",
            field=models.BooleanField(default=False, verbose_name="邮件订阅布料更新"),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="邮箱已验证"),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="邮箱验证令牌"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="验证令牌过期时间"
            ),
        ),
    ]
