# Generated by Django 5.2 on 2025-04-27 01:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "fabric_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="面料唯一ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="面料编号"
                    ),
                ),
                (
                    "merchant_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="面料商编号"
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="面料参考码",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="面料图片URL",
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="幅宽"
                    ),
                ),
                (
                    "yarn_count",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="纱支"
                    ),
                ),
                (
                    "density",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="密度"
                    ),
                ),
                ("weight", models.CharField(max_length=50, verbose_name="克重")),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("gsm", "gsm"), ("mm", "mm")],
                        default="gsm",
                        max_length=5,
                        verbose_name="重量单位",
                    ),
                ),
                (
                    "fabric_type",
                    models.CharField(
                        choices=[("针织", "针织"), ("梭织", "梭织"), ("蕾丝", "蕾丝")],
                        default="针织",
                        max_length=10,
                        verbose_name="面料类型",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="布面风格"
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工艺"
                    ),
                ),
                (
                    "craft_options",
                    models.JSONField(blank=True, default=list, verbose_name="工艺选项"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "main_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fabric",
                        to="base.image",
                        verbose_name="主图片",
                    ),
                ),
            ],
            options={
                "verbose_name": "面料",
                "verbose_name_plural": "面料",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "component_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="成分唯一ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="成分名称")),
                ("percentage", models.FloatField(verbose_name="成分百分比")),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="fabrics.fabric",
                        verbose_name="所属面料",
                    ),
                ),
            ],
            options={
                "verbose_name": "面料成分",
                "verbose_name_plural": "面料成分",
            },
        ),
    ]
