# Generated by Django 5.2 on 2025-05-03 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "option_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="选项唯一ID",
                    ),
                ),
                (
                    "category_code",
                    models.CharField(
                        choices=[
                            ("COMPONENT", "成分"),
                            ("CRAFT", "工艺"),
                            ("FABRIC_STYLE", "布面风格"),
                        ],
                        default="COMPONENT",
                        max_length=20,
                        verbose_name="选项类别",
                    ),
                ),
                (
                    "option_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="选项编码",
                    ),
                ),
                (
                    "option_name",
                    models.CharField(max_length=100, verbose_name="选项名称"),
                ),
            ],
            options={
                "verbose_name": "通用选项",
                "verbose_name_plural": "通用选项",
                "ordering": ["category_code", "option_name"],
            },
        ),
        migrations.AddField(
            model_name="component",
            name="option_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="成分选项编码"
            ),
        ),
    ]
