# Generated by Django 5.2 on 2025-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0002_option_component_option_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabric",
            name="process_codes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="工艺选项编码"
            ),
        ),
        migrations.AddField(
            model_name="fabric",
            name="style_codes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="布面风格选项编码"
            ),
        ),
    ]
