# Generated by Django 5.2 on 2025-05-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0003_fabric_process_codes_fabric_style_codes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fabric",
            name="process",
        ),
        migrations.RemoveField(
            model_name="fabric",
            name="style",
        ),
    ]
