# Generated by Django 5.2 on 2025-05-03 13:38

from django.db import migrations, models


def convert_fabric_type_to_code(apps, schema_editor):
    """将面料类型从文本转换为代码"""
    Fabric = apps.get_model('fabrics', 'Fabric')
    
    # 定义映射关系
    type_mapping = {
        '针织': 1,
        '梭织': 2,
        '蕾丝': 3
    }
    
    # 更新所有面料
    for fabric in Fabric.objects.all():
        # 根据文本值设置正确的整数值
        fabric_type_text = fabric.fabric_type_old
        fabric.fabric_type = type_mapping.get(fabric_type_text, 1)  # 默认为1（针织）
        fabric.save(update_fields=['fabric_type'])


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0004_remove_fabric_process_remove_fabric_style"),
    ]

    operations = [
        # 1. 重命名当前字段为fabric_type_old
        migrations.RenameField(
            model_name='fabric',
            old_name='fabric_type',
            new_name='fabric_type_old',
        ),
        
        # 2. 添加新的整数类型字段
        migrations.AddField(
            model_name='fabric',
            name='fabric_type',
            field=models.IntegerField(
                choices=[(1, "针织"), (2, "梭织"), (3, "蕾丝")],
                default=1,
                verbose_name="面料类型",
            ),
        ),
        
        # 3. 将旧值转换为新值
        migrations.RunPython(convert_fabric_type_to_code),
        
        # 4. 删除旧字段
        migrations.RemoveField(
            model_name='fabric',
            name='fabric_type_old',
        ),
    ]
