# Generated by Django 5.2 on 2025-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0006_vendor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["sort_order", "category_code"],
                "verbose_name": "通用选项",
                "verbose_name_plural": "通用选项",
            },
        ),
        migrations.AddField(
            model_name="option",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="排序顺序"),
        ),
    ]
