# Generated by Django 5.2 on 2025-05-18 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0007_alter_option_options_option_sort_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="记录ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=50, verbose_name="IP地址")),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "referer",
                    models.TextField(blank=True, null=True, verbose_name="来源页面"),
                ),
                (
                    "page_viewed",
                    models.CharField(
                        default="fabric_preview",
                        max_length=100,
                        verbose_name="访问页面",
                    ),
                ),
                (
                    "visit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
            ],
            options={
                "verbose_name": "访客记录",
                "verbose_name_plural": "访客记录",
                "ordering": ["-visit_time"],
            },
        ),
    ]
