# Generated by Django 5.2 on 2025-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0008_visitorlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabric",
            name="weight",
            field=models.FloatField(verbose_name="克重"),
        ),
    ]
