# Generated by Django 5.2 on 2025-08-24 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_user_email_subscription_user_email_verified_and_more"),
        ("fabrics", "0009_alter_fabric_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabric",
            name="fabric_type",
            field=models.IntegerField(
                choices=[(1, "针织"), (2, "梭织"), (3, "蕾丝"), (4, "天鹅绒")],
                default=1,
                verbose_name="面料类型",
            ),
        ),
        migrations.CreateModel(
            name="FavoriteShare",
            fields=[
                (
                    "share_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="分享ID",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分享令牌"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="查看次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分享时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_favorites",
                        to="base.user",
                        verbose_name="分享用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏分享",
                "verbose_name_plural": "收藏分享",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FabricFavorite",
            fields=[
                (
                    "favorite_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="收藏ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="fabrics.fabric",
                        verbose_name="面料",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="base.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "面料收藏",
                "verbose_name_plural": "面料收藏",
                "ordering": ["-created_at"],
                "unique_together": {("user", "fabric")},
            },
        ),
    ]
