version: '3.8'

services:
  web:
    image: ${DOCKER_IMAGE}
    restart: always
    # 显式指定entrypoint为bash，然后在command中执行脚本
    entrypoint: ["/bin/bash"]
    command: ["-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"]
    # 不要挂载覆盖Python模块，只挂载数据目录
    # volumes:
      # - ./staticfiles:/app/staticfiles # 移除或注释掉这行
      # 如果你需要持久化media文件，可以添加这个:
      # - ./media:/app/media
    ports:
      - "18083:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=fabric.settings
      - PYTHONPATH=/app
      - DJANGO_ENV=production
    networks: # 将 web 服务连接到 fabric_network
      - shared_net 

# 顶层 networks 定义
networks:
  shared_net: # 这是你在 service 中引用的逻辑名称
    external: true # 关键：标记为使用外部网络
    name: 1panel-network # 可选：指定实际存在的外部网络名称