location = /grid {
    return 301 /grid/;
}

location /grid/ {
    alias /opt/1panel/apps/openresty/openresty/www/sites/fabricoption.com/table/dist/;
    index index.html;
    try_files $uri $uri/ /grid/index.html;
}
