#!/usr/bin/env bash
# 按数据库/存储配置生成 docker-compose.yml（由 install-lib / deploy/install.sh source）

# FABRIC_DB_PROFILE: sqlite | embedded | external | setup
# FABRIC_STORAGE_PROFILE: local | minio | external-s3 | setup

install_lib_compose_services_to_pull() {
  local db_eff
  db_eff="$(install_lib_effective_db_profile)"
  COMPOSE_PULL_SERVICES=(api todo-web gateway)
  case "$db_eff" in
    embedded)
      COMPOSE_PULL_SERVICES+=(postgres redis)
      ;;
    external)
      COMPOSE_PULL_SERVICES+=(redis)
      ;;
  esac
  case "${FABRIC_STORAGE_PROFILE:-local}" in
    minio)
      COMPOSE_PULL_SERVICES+=(minio minio-init)
      ;;
  esac
}

install_lib_generate_compose() {
  local target="${1:-docker-compose.yml}"
  local db_eff storage db_mode storage_mode
  db_eff="$(install_lib_effective_db_profile)"
  storage="${FABRIC_STORAGE_PROFILE:-local}"
  db="$db_eff"
  local api_depends=()

  case "$db_eff" in
    external)
      db_mode=external
      ;;
    *)
      db_mode=embedded
      db=embedded
      ;;
  esac

  case "$storage" in
    minio)
      storage_mode=embedded-minio
      ;;
    external-s3)
      storage_mode=external-s3
      ;;
    setup)
      storage_mode=local
      storage=local
      ;;
    *)
      storage_mode=local
      storage=local
      ;;
  esac

  DATABASE_MODE="$db_mode"
  STORAGE_MODE="$storage_mode"

  if [[ "$db_eff" == "embedded" ]]; then
    api_depends+=("postgres")
  fi
  api_depends+=("redis")
  if [[ "$storage" == "minio" ]]; then
    api_depends+=("minio-init")
  fi

  {
    cat <<'HEADER'
# Generated by Fabric install — do not edit by hand
name: fabric

services:
HEADER

    if [[ "$db_eff" == "embedded" ]]; then
      cat <<'PG'
  postgres:
    image: postgres:16-alpine
    container_name: fabric-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fabric}
      POSTGRES_USER: ${POSTGRES_USER:-fabric}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}
    volumes:
      - fabric_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-fabric} -d ${POSTGRES_DB:-fabric}"]
      interval: 5s
      timeout: 5s
      retries: 12

PG
    fi

    cat <<'REDIS'
  redis:
    image: redis:7-alpine
    container_name: fabric-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

REDIS

    if [[ "$storage" == "minio" ]]; then
      cat <<'MINIO'
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: fabric-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-fabric}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?set MINIO_ROOT_PASSWORD in .env}
    volumes:
      - fabric_minio_data:/data

  minio-init:
    image: minio/mc:latest
    container_name: fabric-minio-init
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-fabric}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD 2>/dev/null; do
        echo 'waiting for minio...'; sleep 2;
      done;
      mc mb --ignore-existing local/${MINIO_BUCKET:-fabric}
      "
    restart: "no"

MINIO
    fi

    cat <<'API_HEAD'
  api:
    image: ${FABRIC_IMAGE_API:?set FABRIC_IMAGE_API}
    container_name: fabric-api
    restart: unless-stopped
    pull_policy: always
    volumes:
      - fabric_data:/app/data
    environment:
      APP_ENV: production
      HTTP_ADDR: ":8080"
      JWT_SECRET: ${JWT_SECRET:?set JWT_SECRET in .env}
      JWT_ISSUER: todo-server-go
      MIGRATIONS_DIR: /app/db/migrations
      REDIS_ADDR: redis:6379
      DATA_DIR: /app/data
      DATABASE_MODE: ${DATABASE_MODE:-embedded}
      STORAGE_MODE: ${STORAGE_MODE:-local}
      LOCAL_STORAGE_PATH: /app/data/files
      BOOTSTRAP_ADMIN_USER: ${BOOTSTRAP_ADMIN_USER:-admin}
      BOOTSTRAP_ADMIN_PASSWORD: ${BOOTSTRAP_ADMIN_PASSWORD:?set BOOTSTRAP_ADMIN_PASSWORD in .env}
      BOOTSTRAP_ADMIN_EMAIL: admin@local

API_HEAD

    if [[ "$db_eff" == "embedded" ]]; then
      cat <<'API_EMBED_DB'
      POSTGRES_DSN: postgres://${POSTGRES_USER:-fabric}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-fabric}?sslmode=disable
      POSTGRES_DB: ${POSTGRES_DB:-fabric}
      DATABASE_HOST_DISPLAY: postgres

API_EMBED_DB
    else
      cat <<'API_EXT_DB'
      POSTGRES_DSN: ${POSTGRES_DSN:?set POSTGRES_DSN in .env}
      POSTGRES_DB: ${POSTGRES_DB:-fabric}
      DATABASE_HOST_DISPLAY: ${DATABASE_HOST_DISPLAY:-external}

API_EXT_DB
    fi

    if [[ "$storage" == "minio" ]]; then
      cat <<'API_MINIO'
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-fabric}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET:-fabric}
      MINIO_SECURE: "false"

API_MINIO
    fi

    cat <<'API_HEALTH'
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8080/healthz"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

API_HEALTH

    # depends_on block
    echo "    depends_on:"
    if [[ "$db_eff" == "embedded" ]]; then
      echo "      postgres:"
      echo "        condition: service_healthy"
    fi
    echo "      redis:"
    echo "        condition: service_healthy"
    if [[ "$storage" == "minio" ]]; then
      echo "      minio-init:"
      echo "        condition: service_completed_successfully"
    fi

    cat <<'REST'
  todo-web:
    image: ${FABRIC_IMAGE_WEB:?set FABRIC_IMAGE_WEB}
    container_name: fabric-web
    restart: unless-stopped
    pull_policy: always

  gateway:
    image: nginx:1.27-alpine
    container_name: fabric-gateway
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
      todo-web:
        condition: service_started
    ports:
      - "${HTTP_PORT:-8088}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  fabric_data:
REST

    if [[ "$db_eff" == "embedded" ]]; then
      echo "  fabric_pg_data:"
    fi
    if [[ "$storage" == "minio" ]]; then
      echo "  fabric_minio_data:"
    fi
  } > "$target"
}
