# Generated by Django 5.2 on 2025-04-27 01:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GridProject",
            fields=[
                (
                    "project_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="项目ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="项目名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="项目描述"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="是否归档"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grid_projects",
                        to="base.user",
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "网格项目",
                "verbose_name_plural": "网格项目",
                "db_table": "grid_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GridColumn",
            fields=[
                (
                    "column_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="列ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="列标题")),
                ("width", models.IntegerField(default=100, verbose_name="列宽")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("image", "图片"),
                            ("file", "文件"),
                            ("vendor", "供应商"),
                            ("date", "日期"),
                            ("vendorNote", "供应商备注"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="列类型",
                    ),
                ),
                ("column_index", models.IntegerField(verbose_name="列索引")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="grid.gridproject",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "网格列",
                "verbose_name_plural": "网格列",
                "db_table": "grid_column",
                "ordering": ["column_index"],
                "unique_together": {("project", "column_index")},
            },
        ),
        migrations.CreateModel(
            name="GridRow",
            fields=[
                (
                    "row_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="行ID",
                    ),
                ),
                ("row_index", models.IntegerField(verbose_name="行索引")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="grid.gridproject",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "网格行",
                "verbose_name_plural": "网格行",
                "db_table": "grid_row",
                "ordering": ["row_index"],
                "unique_together": {("project", "row_index")},
            },
        ),
        migrations.CreateModel(
            name="GridCell",
            fields=[
                (
                    "cell_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="单元格ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="内容"),
                ),
                ("style", models.TextField(blank=True, null=True, verbose_name="样式")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("image", "图片"),
                            ("file", "文件"),
                            ("vendor", "供应商"),
                            ("date", "日期"),
                            ("vendorNote", "供应商备注"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="单元格类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="grid.gridcolumn",
                        verbose_name="所属列",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="grid.gridrow",
                        verbose_name="所属行",
                    ),
                ),
            ],
            options={
                "verbose_name": "网格单元格",
                "verbose_name_plural": "网格单元格",
                "db_table": "grid_cell",
                "unique_together": {("row", "column")},
            },
        ),
    ]
