# Generated by Django 5.2 on 2025-04-27 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GridShared",
            fields=[
                (
                    "shared_id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="共享ID",
                    ),
                ),
                (
                    "shared_key",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="共享密钥"
                    ),
                ),
                (
                    "shared_password",
                    models.CharField(max_length=4, verbose_name="共享密码"),
                ),
                (
                    "vender",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="厂商"
                    ),
                ),
                (
                    "row_ids",
                    models.TextField(blank=True, null=True, verbose_name="行IDs"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_links",
                        to="grid.gridproject",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "网格共享",
                "verbose_name_plural": "网格共享",
                "db_table": "grid_shared",
                "ordering": ["-created_at"],
            },
        ),
    ]
