# Generated by Django 5.2 on 2025-04-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid", "0002_gridshared"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridshared",
            name="vender_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="厂商ID"
            ),
        ),
    ]
