# Generated by Django 5.2 on 2025-04-28 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid", "0003_gridshared_vender_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gridcell",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="gridcell",
            name="project",
            field=models.ForeignKey(
                default="9093bf78-4420-4fc5-900d-e3e2cc6c172c",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cells",
                to="grid.gridproject",
                verbose_name="所属项目",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="gridcell",
            unique_together={("project", "row", "column")},
        ),
    ]
