# Generated by Django 5.2 on 2025-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid", "0004_alter_gridcell_unique_together_gridcell_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridcolumn",
            name="rule",
            field=models.TextField(blank=True, null=True, verbose_name="限制规则"),
        ),
        migrations.AddField(
            model_name="gridcolumn",
            name="style",
            field=models.TextField(blank=True, null=True, verbose_name="样式配置"),
        ),
        migrations.AddField(
            model_name="gridrow",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="是否隐藏"),
        ),
    ]
