# Generated by Django 5.2 on 2025-05-05 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0006_vendor"),
        ("grid", "0005_gridcolumn_rule_gridcolumn_style_gridrow_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="GridVendorShare",
            fields=[
                (
                    "vendor_share_id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="供应商共享ID",
                    ),
                ),
                (
                    "shared_key",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="共享密钥"
                    ),
                ),
                (
                    "shared_password",
                    models.CharField(max_length=4, verbose_name="共享密码"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "row_ids",
                    models.TextField(blank=True, null=True, verbose_name="行IDs"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_shares",
                        to="grid.gridproject",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grid_shares",
                        to="fabrics.vendor",
                        verbose_name="供应商",
                    ),
                ),
            ],
            options={
                "verbose_name": "网格供应商共享",
                "verbose_name_plural": "网格供应商共享",
                "db_table": "grid_vendor_share",
                "ordering": ["-created_at"],
            },
        ),
    ]
