# Generated by Django 5.2 on 2025-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0007_alter_option_options_option_sort_order"),
        ("grid", "0006_gridvendorshare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gridvendorshare",
            name="is_active",
            field=models.BooleanField(default=True, null=True, verbose_name="是否激活"),
        ),
        migrations.AlterUniqueTogether(
            name="gridvendorshare",
            unique_together={("project", "vendor")},
        ),
    ]
