ALTER TABLE fabrics ADD COLUMN IF NOT EXISTS width VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE fabrics ADD COLUMN IF NOT EXISTS yarn_count VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE fabrics ADD COLUMN IF NOT EXISTS density VARCHAR(64) NOT NULL DEFAULT '';
